name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    env:
      MARIADB_USER: ${{ secrets.TEST_MARIADB_USER }}
      MARIADB_PASSWORD: ${{ secrets. TEST_MARIADB_PASSWORD }}
      MARIADB_DATABASE: ${{ secrets. MARIADB_DATABASE }}
      DATABASE_HOST: ${{ secrets.TEST_MARIADB_SERVER }}
      DJANGO_SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
      HOST_SERVERNAME: http://localhost:8000
      DEBUG: FALSE
      HOST_IP: 0.0.0.0
      
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9.1]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Run Tests
      run: |
        python backend/project/manage.py test

#  deploy:
#    needs: build
#    
#    runs-on: ubuntu-18.04
