name: Django CI

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-18.04
    environment: test_environment
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9.1]

    steps:
    - name: Test secrets
      run: |
        echo $DJANGO_SECRET_KEY | rev
        echo ${{ secrets.DJANGO_SERCET_KEY }} | rev
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Run Tests
      run: |
        python backend/project/manage.py test

#  deploy:
#    needs: build
#    
#    runs-on: ubuntu-18.04
